### ISSUE TITLE
Questions about HoughCircle API

### ISSUE THREAD

**Issue by sonnyproto** [AdityaMulgundkar/flutter_opencv#23]
Hi, thank you for your great works. I'm a student currently doing a university project to perform Iris and pupil detection for covid patients. For HoughCircle API, could I ask whether there's any way to get the detected circles' radius only instead of the whole processed output picture?

**Comment by gijso** [comment]
Did you manage to fix this somehow?

**Comment by fredmo** [comment]
Same question, could you return with the API, the circle "x y r" detected?

**Comment by sonnyproto** [comment]
Closed due to the lack of response.

**Comment by fredmo** [comment]
I will reopen this issue in a new thread

Cf Pull Request : https://github.com/AdityaMulgundkar/flutter_opencv/pull/30
