### ISSUE TITLE
Need some guidance in adding bindings for `grabCut`

### ISSUE THREAD

**Issue by ralienpp** [AdityaMulgundkar/flutter_opencv#8]
**Is the requested feature available in the C++/Java/Python interfaces for OpenCV?**
It is available in OpenCV and the bindings for Python and Java, example: https://www.docs.opencv.org/trunk/d7/d1b/group__imgproc__misc.html#ga909c1dda50efcbeaa3ce126be862b37f

I need it for a pet project I'm working on, and overall I think it would be beneficial to have it in `flutter_opencv` because it will make the bindings more complete.

I've followed the guidelines in the readme and here is my current draft implementation: https://github.com/AdityaMulgundkar/flutter_opencv/pull/7#

Note that I've hardcoded some of the things (number of iterations, the rectangle, etc.) because I am just exploring the feasibility of this approach. Although the code runs without an error, the result is a black image.

`grabCut` is a bit tricky, because it uses an `InputOutputArray` variable, which is not featured in any of the existing wrapper-functions and is not mentioned in the readme either. Something might be odd with `dst`, perhaps it has to be initialized somehow.

@AdityaMulgundkar, can you provide some guidance? Your assistance would be greatly appreciated, thank you forward.

**Comment by AdityaMulgundkar** [comment]
Hey @ralienpp This has been implemented in v1.0.4. You can test it out yourself by updating your version of opencv to v1.0.4.
